// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeO3-uzegdwmpD_WPD-LVgmLo6E2q-iiY',
    appId: '1:22573562429:web:f9cf760303c2edcec24854',
    messagingSenderId: '22573562429',
    projectId: 'wassalny-de40d',
    authDomain: 'wassalny-de40d.firebaseapp.com',
    storageBucket: 'wassalny-de40d.firebasestorage.app',
    measurementId: 'G-80489MHP7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYAYkbWImUxeA0hC_Cz0bxuQAjMsYSrwg',
    appId: '1:22573562429:android:3bbaaefd23b5edbec24854',
    messagingSenderId: '22573562429',
    projectId: 'wassalny-de40d',
    storageBucket: 'wassalny-de40d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVDNvC7aRAVEZO2mY48V9HBntMMvdQbbA',
    appId: '1:22573562429:ios:035538272c71f7e7c24854',
    messagingSenderId: '22573562429',
    projectId: 'wassalny-de40d',
    storageBucket: 'wassalny-de40d.firebasestorage.app',
    iosBundleId: 'com.example.wassalnyCaptain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVDNvC7aRAVEZO2mY48V9HBntMMvdQbbA',
    appId: '1:22573562429:ios:035538272c71f7e7c24854',
    messagingSenderId: '22573562429',
    projectId: 'wassalny-de40d',
    storageBucket: 'wassalny-de40d.firebasestorage.app',
    iosBundleId: 'com.example.wassalnyCaptain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeO3-uzegdwmpD_WPD-LVgmLo6E2q-iiY',
    appId: '1:22573562429:web:93575853021b3d8cc24854',
    messagingSenderId: '22573562429',
    projectId: 'wassalny-de40d',
    authDomain: 'wassalny-de40d.firebaseapp.com',
    storageBucket: 'wassalny-de40d.firebasestorage.app',
    measurementId: 'G-YN0L5PBVMF',
  );
}
